
-- Rename Copy Tables

DROP TABLE CUSTOMERS PURGE;

RENAME CUSTOMERS_C to CUSTOMERS;

DROP TABLE ADDRESSES PURGE;

RENAME ADDRESSES_C to ADDRESSES;

DROP TABLE CARD_DETAILS PURGE;

RENAME CARD_DETAILS_C to CARD_DETAILS;

DROP TABLE ORDERS PURGE;

RENAME ORDERS_C to ORDERS;

DROP TABLE ORDER_ITEMS PURGE;

RENAME ORDER_ITEMS_C to ORDER_ITEMS;

-- End Script