
-- Rename Copy Tables

DROP TABLE CUSTOMERS PURGE;

DROP TABLE SUPPLEMENTARY_DEMOGRAPHICS PURGE;

DROP TABLE SALES PURGE;

RENAME CUSTOMERS_C to CUSTOMERS;

RENAME SUPPLEMENTARY_DEMOGRAPHICS_C to SUPPLEMENTARY_DEMOGRAPHICS;

RENAME SALES_C to SALES;

-- End Script
