REM SH CUSTOMERS_MARITAL_BIX

CREATE BITMAP INDEX CUSTOMERS_MARITAL_BIX ON CUSTOMERS (CUST_MARITAL_STATUS) TABLESPACE &indextablespace &parallelclause &logging LOCAL;

REM SH CUSTOMERS_YOB_BIX

CREATE BITMAP INDEX CUSTOMERS_YOB_BIX ON CUSTOMERS (CUST_YEAR_OF_BIRTH) TABLESPACE &indextablespace &parallelclause &logging LOCAL;

REM SH CUSTOMERS_GENDER_BIX

CREATE BITMAP INDEX CUSTOMERS_GENDER_BIX ON CUSTOMERS (CUST_GENDER) TABLESPACE &indextablespace &parallelclause &logging LOCAL;


REM SH PRODUCTS_PROD_STATUS_BIX

CREATE BITMAP INDEX PRODUCTS_PROD_STATUS_BIX ON PRODUCTS (PROD_STATUS) TABLESPACE &indextablespace &parallelclause &logging;


REM SH PRODUCTS_PROD_SUBCAT_IX

CREATE INDEX PRODUCTS_PROD_SUBCAT_IX ON PRODUCTS (PROD_SUBCATEGORY) TABLESPACE &indextablespace &parallelclause &logging;

REM SH PRODUCTS_PROD_CAT_IX

CREATE INDEX PRODUCTS_PROD_CAT_IX ON PRODUCTS (PROD_CATEGORY) TABLESPACE &indextablespace &parallelclause &logging;

REM SH SALES_PROD_BIX

CREATE BITMAP INDEX SALES_PROD_BIX ON SALES (PROD_ID) TABLESPACE &indextablespace &parallelclause &logging LOCAL;

REM SH SALES_CUST_BIX

CREATE BITMAP INDEX SALES_CUST_BIX ON SALES (CUST_ID) TABLESPACE &indextablespace &parallelclause &logging LOCAL;

REM SH SALES_TIME_BIX

-- CREATE BITMAP INDEX SALES_TIME_BIX ON SALES (TIME_ID) TABLESPACE &indextablespace &parallelclause &logging LOCAL;

REM SH SALES_CHANNEL_BIX

CREATE BITMAP INDEX SALES_CHANNEL_BIX ON SALES (CHANNEL_ID) TABLESPACE &indextablespace &parallelclause &logging LOCAL;

REM SH SALES_PROMO_BIX

CREATE BITMAP INDEX SALES_PROMO_BIX ON SALES (PROMO_ID) TABLESPACE &indextablespace &parallelclause &logging LOCAL;

-- End;

