ALTER TABLE sales EXCHANGE PARTITION SALES_1995 WITH TABLE SALES_1995 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_1996 WITH TABLE SALES_1996 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_H1_1997 WITH TABLE SALES_H1_1997 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_H2_1997 WITH TABLE SALES_H2_1997 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_1998 WITH TABLE SALES_Q1_1998 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_1998 WITH TABLE SALES_Q2_1998 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_1998 WITH TABLE SALES_Q3_1998 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_1998 WITH TABLE SALES_Q4_1998 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_1999 WITH TABLE SALES_Q1_1999 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_1999 WITH TABLE SALES_Q2_1999 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_1999 WITH TABLE SALES_Q3_1999 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_1999 WITH TABLE SALES_Q4_1999 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2000 WITH TABLE SALES_Q1_2000 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2000 WITH TABLE SALES_Q2_2000 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2000 WITH TABLE SALES_Q3_2000 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2000 WITH TABLE SALES_Q4_2000 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2001 WITH TABLE SALES_Q1_2001 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2001 WITH TABLE SALES_Q2_2001 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2001 WITH TABLE SALES_Q3_2001 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2001 WITH TABLE SALES_Q4_2001 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2002 WITH TABLE SALES_Q1_2002 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2002 WITH TABLE SALES_Q2_2002 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2002 WITH TABLE SALES_Q3_2002 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2002 WITH TABLE SALES_Q4_2002 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2003 WITH TABLE SALES_Q1_2003 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2003 WITH TABLE SALES_Q2_2003 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2003 WITH TABLE SALES_Q3_2003 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2003 WITH TABLE SALES_Q4_2003 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2004 WITH TABLE SALES_Q1_2004 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2004 WITH TABLE SALES_Q2_2004 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2004 WITH TABLE SALES_Q3_2004 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2004 WITH TABLE SALES_Q4_2004 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2005 WITH TABLE SALES_Q1_2005 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2005 WITH TABLE SALES_Q2_2005 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2005 WITH TABLE SALES_Q3_2005 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2005 WITH TABLE SALES_Q4_2005 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2006 WITH TABLE SALES_Q1_2006 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2006 WITH TABLE SALES_Q2_2006 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2006 WITH TABLE SALES_Q3_2006 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2006 WITH TABLE SALES_Q4_2006 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2007 WITH TABLE SALES_Q1_2007 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2007 WITH TABLE SALES_Q2_2007 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2007 WITH TABLE SALES_Q3_2007 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2007 WITH TABLE SALES_Q4_2007 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2008 WITH TABLE SALES_Q1_2008 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2008 WITH TABLE SALES_Q2_2008 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2008 WITH TABLE SALES_Q3_2008 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2008 WITH TABLE SALES_Q4_2008 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2009 WITH TABLE SALES_Q1_2009 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2009 WITH TABLE SALES_Q2_2009 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2009 WITH TABLE SALES_Q3_2009 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2009 WITH TABLE SALES_Q4_2009 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2010 WITH TABLE SALES_Q1_2010 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2010 WITH TABLE SALES_Q2_2010 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2010 WITH TABLE SALES_Q3_2010 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2010 WITH TABLE SALES_Q4_2010 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2011 WITH TABLE SALES_Q1_2011 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2011 WITH TABLE SALES_Q2_2011 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2011 WITH TABLE SALES_Q3_2011 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2011 WITH TABLE SALES_Q4_2011 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2012 WITH TABLE SALES_Q1_2012 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2012 WITH TABLE SALES_Q2_2012 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2012 WITH TABLE SALES_Q3_2012 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2012 WITH TABLE SALES_Q4_2012 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q1_2013 WITH TABLE SALES_Q1_2013 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q2_2013 WITH TABLE SALES_Q2_2013 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q3_2013 WITH TABLE SALES_Q3_2013 WITHOUT VALIDATION;

ALTER TABLE sales EXCHANGE PARTITION SALES_Q4_2013 WITH TABLE SALES_Q4_2013 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS1 WITH TABLE CUSTOMERS1 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS2 WITH TABLE CUSTOMERS2 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS3 WITH TABLE CUSTOMERS3 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS4 WITH TABLE CUSTOMERS4 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS5 WITH TABLE CUSTOMERS5 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS6 WITH TABLE CUSTOMERS6 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS7 WITH TABLE CUSTOMERS7 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS8 WITH TABLE CUSTOMERS8 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS9 WITH TABLE CUSTOMERS9 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS10 WITH TABLE CUSTOMERS10 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS11 WITH TABLE CUSTOMERS11 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS12 WITH TABLE CUSTOMERS12 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS13 WITH TABLE CUSTOMERS13 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS14 WITH TABLE CUSTOMERS14 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS15 WITH TABLE CUSTOMERS15 WITHOUT VALIDATION;

ALTER TABLE customers EXCHANGE PARTITION CUSTOMERS16 WITH TABLE CUSTOMERS16 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART1 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS1 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART2 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS2 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART3 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS3 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART4 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS4 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART5 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS5 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART6 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS6 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART7 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS7 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART8 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS8 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART9 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS9 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART10 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS10 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART11 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS11 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART12 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS12 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART13 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS13 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART14 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS14 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART15 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS15 WITHOUT VALIDATION;

ALTER TABLE SUPPLEMENTARY_DEMOGRAPHICS EXCHANGE PARTITION SUPP_DEM_PART16 WITH TABLE SUPPLEMENTARY_DEMOGRAPHICS16 WITHOUT VALIDATION;

-- End;