CREATE USER euro
  	IDENTIFIED BY euro
  	DEFAULT TABLESPACE USERS
  	TEMPORARY TABLESPACE TEMP
  	ACCOUNT UNLOCK;

GRANT UNLIMITED TABLESPACE TO euro;

GRANT CONNECT, RESOURCE TO euro IDENTIFIED BY euro;

