ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER OGGUSER
  	IDENTIFIED BY welcome1
  	DEFAULT TABLESPACE USERS
  	TEMPORARY TABLESPACE TEMP
  	ACCOUNT UNLOCK;
  	-- 2 Roles for OGGUSER
GRANT CONNECT TO OGGUSER;
GRANT UNLIMITED TABLESPACE TO OGGUSER;
GRANT SELECT ANY DICTIONARY TO OGGUSER;
GRANT DBA TO OGGUSER;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER SYSTEM SWITCH LOGFILE;
SELECT SUPPLEMENTAL_LOG_DATA_MIN FROM V$DATABASE;
DROP USER OGGADM CASCADE;
DROP USER OGGADMDWN CASCADE;
DROP USER CURRENCY_ADMIN CASCADE;
EXIT

