
  CREATE TABLE CHANNELS 
   (	CHANNEL_ID NUMBER NOT NULL ENABLE, 
	CHANNEL_DESC VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	CHANNEL_CLASS VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	CHANNEL_CLASS_ID NUMBER NOT NULL ENABLE, 
	CHANNEL_TOTAL VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	CHANNEL_TOTAL_ID NUMBER NOT NULL ENABLE
   ) ;


  CREATE TABLE COUNTRIES 
   (	COUNTRY_ID NUMBER NOT NULL ENABLE, 
	COUNTRY_ISO_CODE CHAR(2 BYTE) NOT NULL ENABLE, 
	COUNTRY_NAME VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	COUNTRY_SUBREGION VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	COUNTRY_SUBREGION_ID NUMBER NOT NULL ENABLE, 
	COUNTRY_REGION VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	COUNTRY_REGION_ID NUMBER NOT NULL ENABLE, 
	COUNTRY_TOTAL VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	COUNTRY_TOTAL_ID NUMBER NOT NULL ENABLE, 
	COUNTRY_NAME_HIST VARCHAR2(40 BYTE)
   ) ;
 

  CREATE TABLE CUSTOMERS 
   (	CUST_ID NUMBER NOT NULL ENABLE, 
	CUST_FIRST_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	CUST_LAST_NAME VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	CUST_GENDER CHAR(1 BYTE) NOT NULL ENABLE, 
	CUST_YEAR_OF_BIRTH NUMBER(4,0) NOT NULL ENABLE, 
	CUST_MARITAL_STATUS VARCHAR2(20 BYTE), 
	CUST_STREET_ADDRESS VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	CUST_POSTAL_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	CUST_CITY VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	CUST_CITY_ID NUMBER NOT NULL ENABLE, 
	CUST_STATE_PROVINCE VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	CUST_STATE_PROVINCE_ID NUMBER NOT NULL ENABLE, 
	COUNTRY_ID NUMBER NOT NULL ENABLE, 
	CUST_MAIN_PHONE_NUMBER VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	CUST_INCOME_LEVEL VARCHAR2(30 BYTE), 
	CUST_CREDIT_LIMIT NUMBER, 
	CUST_EMAIL VARCHAR2(50 BYTE), 
	CUST_TOTAL VARCHAR2(14 BYTE) NOT NULL ENABLE, 
	CUST_TOTAL_ID NUMBER NOT NULL ENABLE, 
	CUST_SRC_ID NUMBER, 
	CUST_EFF_FROM DATE, 
	CUST_EFF_TO DATE, 
	CUST_VALID VARCHAR2(1 BYTE)	 
   ) &usecompression INITRANS 16 STORAGE (INITIAL 8M NEXT 8M);
 

  CREATE TABLE PROMOTIONS 
   (	PROMO_ID NUMBER(6,0) NOT NULL ENABLE, 
	PROMO_NAME VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	PROMO_SUBCATEGORY VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	PROMO_SUBCATEGORY_ID NUMBER NOT NULL ENABLE, 
	PROMO_CATEGORY VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	PROMO_CATEGORY_ID NUMBER NOT NULL ENABLE, 
	PROMO_COST NUMBER(10,2) NOT NULL ENABLE, 
	PROMO_BEGIN_DATE DATE NOT NULL ENABLE, 
	PROMO_END_DATE DATE NOT NULL ENABLE, 
	PROMO_TOTAL VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	PROMO_TOTAL_ID NUMBER NOT NULL ENABLE
   ) ;
 


  CREATE TABLE PRODUCTS 
   (	PROD_ID NUMBER(6,0) NOT NULL ENABLE, 
	PROD_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	PROD_DESC VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	PROD_SUBCATEGORY VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	PROD_SUBCATEGORY_ID NUMBER NOT NULL ENABLE, 
	PROD_SUBCATEGORY_DESC VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	PROD_CATEGORY VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	PROD_CATEGORY_ID NUMBER NOT NULL ENABLE, 
	PROD_CATEGORY_DESC VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	PROD_WEIGHT_CLASS NUMBER(3,0) NOT NULL ENABLE, 
	PROD_UNIT_OF_MEASURE VARCHAR2(20 BYTE), 
	PROD_PACK_SIZE VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	SUPPLIER_ID NUMBER(6,0) NOT NULL ENABLE, 
	PROD_STATUS VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PROD_LIST_PRICE NUMBER(8,2) NOT NULL ENABLE, 
	PROD_MIN_PRICE NUMBER(8,2) NOT NULL ENABLE, 
	PROD_TOTAL VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	PROD_TOTAL_ID NUMBER NOT NULL ENABLE, 
	PROD_SRC_ID NUMBER, 
	PROD_EFF_FROM DATE, 
	PROD_EFF_TO DATE, 
	PROD_VALID VARCHAR2(1 BYTE)
   ) ;
 


  CREATE TABLE SUPPLEMENTARY_DEMOGRAPHICS 
   (	CUST_ID NUMBER NOT NULL ENABLE, 
	EDUCATION VARCHAR2(21 BYTE), 
	OCCUPATION VARCHAR2(21 BYTE), 
	HOUSEHOLD_SIZE VARCHAR2(21 BYTE), 
	YRS_RESIDENCE NUMBER, 
	AFFINITY_CARD NUMBER(10,0), 
	BULK_PACK_DISKETTES NUMBER(10,0), 
	FLAT_PANEL_MONITOR NUMBER(10,0), 
	HOME_THEATER_PACKAGE NUMBER(10,0), 
	BOOKKEEPING_APPLICATION NUMBER(10,0), 
	PRINTER_SUPPLIES NUMBER(10,0), 
	Y_BOX_GAMES NUMBER(10,0), 
	OS_DOC_SET_KANJI NUMBER(10,0), 
	COMMENTS VARCHAR2(4000 BYTE)
   ) &usecompression INITRANS 16 STORAGE (INITIAL 8M NEXT 8M);
 

  CREATE TABLE SALES 
   (PROD_ID            NUMBER NOT NULL ENABLE,
    CUST_ID            NUMBER NOT NULL ENABLE,
    TIME_ID            DATE NOT NULL ENABLE,
    CHANNEL_ID         NUMBER NOT NULL ENABLE,
    PROMO_ID           NUMBER NOT NULL ENABLE,
    QUANTITY_SOLD      NUMBER(10,2) NOT NULL ENABLE,
    SELLER             NUMBER(6) NOT NULL ENABLE,
    FULFILLMENT_CENTER NUMBER(6) NOT NULL ENABLE,
    COURIER_ORG        NUMBER(6) NOT NULL ENABLE,
    TAX_COUNTRY        VARCHAR2(3) NOT NULL ENABLE,
    TAX_REGION         VARCHAR2(3),
    AMOUNT_SOLD        NUMBER(10,2) NOT NULL ENABLE
   ) &usecompression INITRANS 16 STORAGE (INITIAL 8M NEXT 8M);
   

-- End;
 
