CREATE VIEW SALES_1995 AS SELECT * FROM SALES;

CREATE VIEW SALES_1996 AS SELECT * FROM SALES;

CREATE VIEW SALES_H1_1997 AS SELECT * FROM SALES;

CREATE VIEW SALES_H2_1997  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_1998  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_1998  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_1998  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_1998  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_1999  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_1999  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_1999  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_1999  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2000  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2000  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2000  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2000  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2001  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2001  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2001  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2001  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2002  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2002  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2002  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2002  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2003  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2003  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2003  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2003  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2004  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2004  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2004  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2004  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2005  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2005  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2005  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2005  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2006  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2006  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2006 AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2006  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2007  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2007  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2007  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2007  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2008  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2008  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2008  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2008  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2009  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2009  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2009  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2009  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2010  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2010  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2010  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2010  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2011  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2011  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2011  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2011  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2012  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2012  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2012  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2012  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q1_2013  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q2_2013  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q3_2013  AS SELECT * FROM SALES;

CREATE VIEW SALES_Q4_2013  AS SELECT * FROM SALES;

CREATE VIEW CUSTOMERS1 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS2 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS3 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS4 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS5 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS6 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS7 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS8 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS9 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS10 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS11 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS12 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS13 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS14 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS15 AS SELECT * FROM CUSTOMERS;

CREATE VIEW CUSTOMERS16 AS SELECT * FROM CUSTOMERS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS1 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS2 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS3 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS4 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS5 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS6 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS7 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS8 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS9 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS10 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS11 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS12 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS13 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS14 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS15 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;

CREATE VIEW SUPPLEMENTARY_DEMOGRAPHICS16 AS SELECT * FROM SUPPLEMENTARY_DEMOGRAPHICS;


-- End;
