CREATE USER amer
  	IDENTIFIED BY amer
  	DEFAULT TABLESPACE USERS
  	TEMPORARY TABLESPACE TEMP
  	ACCOUNT UNLOCK;

GRANT UNLIMITED TABLESPACE TO amer;

GRANT CONNECT, RESOURCE TO amer IDENTIFIED BY amer;

